## Array zeros

In [5]:
import numpy as np
x= np.zeros((3,4))
x[0][0] = 0; x[0][1] = 2; x[0][2] =0; x[0][3]=0
x[1][0] = 0; x[1][1] = 2; x[1][2] =0; x[1][3]=0
x[2][0] = 0; x[2][1] = 2; x[2][2] =0; x[2][3]=0
for i in range(3):
    for j in range(4):
        x[i][j]= 0
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Random data SUM (최대한 간단하게)

In [28]:
import numpy as np
x=np.array([[22,3,4] , [2,2,3]]) # [[x1,x2,x3],[x1,x2,x3]] x1을 몸무게 x2는 나이 x3를 수면량이라고 가정
y= ([100,150]) # 1번사람의 혈압이 100 2번사람의 혈압이 150일때
w= ([3,5,8]) # x1의 w값 3 x2의 w값 5 x3의 w값 8
y1= x*w  #([22*3, 3*5, 4*8]) , [2*3, 2*5, 3*8]
y_hat =[]
for i in y1:
    y_hat.append(i.sum())
y_hat


# np.array(x).sum()

[113, 40]

NA값(not available) :값이 들어가지 않거나 계산 불가한 경우 나오는 값

In [32]:
number = [x for x in range(10)]
number
# ==
# number =[]
# for x in range(10):
#     number.append(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]